apiVersion: apps/v1
kind: Deployment
metadata: 
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template: #contains defination of containers in a pod
    metadata:
      label:
        component: web
    spec:
      containers:
        - name: client
          image: nikhil133/checkpoint-client-k8
          ports:
            - containerPort: 3000 